"""add Roasted Coffees

Revision ID: 3a6a643aba47
Revises: ed103ba7a449
Create Date: 2020-05-01 11:21:07.849976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6a643aba47'
down_revision = 'ed103ba7a449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roasted_coffee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roaster', sa.String(length=40), nullable=True),
    sa.Column('roast_date', sa.String(length=14), nullable=True),
    sa.Column('tasting_notes', sa.String(length=120), nullable=True),
    sa.Column('origin_country', sa.String(length=30), nullable=True),
    sa.Column('farm_information', sa.String(length=120), nullable=True),
    sa.Column('coffee_name', sa.String(length=80), nullable=True),
    sa.Column('roast_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roast_session_id'], ['roast_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roasted_coffee')
    # ### end Alembic commands ###
