"""add roast sessions

Revision ID: ed103ba7a449
Revises: 702662eca052
Create Date: 2020-04-30 15:04:42.373933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed103ba7a449'
down_revision = '702662eca052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roast_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('green_coffee_id', sa.Integer(), nullable=True),
    sa.Column('green_weight', sa.Integer(), nullable=True),
    sa.Column('roasted_weight', sa.Integer(), nullable=True),
    sa.Column('roast_time', sa.Integer(), nullable=True),
    sa.Column('fc_time', sa.Integer(), nullable=True),
    sa.Column('roast_date', sa.String(length=20), nullable=True),
    sa.Column('temp_data', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['green_coffee_id'], ['green_coffee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roast_session')
    # ### end Alembic commands ###
